apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: surrealdb/surrealdb:latest
          command: ["/surreal"]
          args: ["start", "--log", "trace", "--user", "root", "--pass", "root"]
---
apiVersion: v1
kind: Service
metadata:
  name: database-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - name: database-port
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: database-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: database
  ports:
    - name: database-load-balancer-port
      protocol: TCP
      port: 8000
      targetPort: 8000

