# Run from the root of the project with `make dev`
apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    concurrency: 0
  artifacts:
    - image: dormammun/gravity-hub
      context: ./application
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
          - src: src/**/*.tsx
            dest: .
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.GIT_COMMIT_SHORT}}"
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/system/*.yaml
      - ./infrastructure/k8s/services/*.yaml
      - ./infrastructure/k8s/providers/*.yaml
